### ISSUE TITLE
Hello. Will you continue to support this project?

### ISSUE THREAD

**Issue by gawric** [shnok/l2-unity#1]
Hello. Will you continue to support this project?
I want to help you develop this client, but my skill is good in c#/java server developer.
Can you write a manual on how you port textures/sounds?
I assume that the main problem is with 3d conversion

**Comment by shnok** [comment]
Hi, yes it is planned, I only work on this project this while feeling bored/have no games to play. 

- I export textures and sounds from the game using [umodel ](https://www.gildor.org/en/projects/umodel)
- 3D conversion is done using a blender [plugin ](https://github.com/DarklightGames/io_scene_psk_psa)
- Metadata is exported using [l2pe ](https://github.com/acmi/L2pe)

I replied to a few [questions ](https://gitlab.com/shnok/l2-unity/-/issues/?sort=created_date&state=all&first_page_size=20) of a guy on gitlab if you are interested. Also you can watch this [video ](https://www.youtube.com/watch?v=IEHY37bJ7nk) that helped me a lot.

**Comment by gawric** [comment]
Thanks it will help.
I have already launched your project and am starting to port the shorcut panel and system panel.
After completion, I will create a pull request.

**Comment by gawric** [comment]
do you use upscale services?

**Comment by shnok** [comment]
> do you use upscale services?

I used it on a few ground textures for testing.

> Thanks it will help. I have already launched your project and am starting to port the shorcut panel and system panel. After completion, I will create a pull request.

Thats great to hear thanks

**Comment by shnok** [comment]
Hi, if you have any questions, I made a discord server for the project.

 https://discord.gg/ra3BmraPKp
