### ISSUE TITLE
Equip BodyPart

### ISSUE THREAD

**Issue by gawric** [shnok/l2-unity#40]
![image](https://github.com/user-attachments/assets/0835df05-7977-4d74-aec9-7f5ea7228259)

usually you use BodyPart in your code, but there is clearly an error using slot

**Comment by gawric** [comment]
line120

**Comment by shnok** [comment]
item Bodypart is never changed server side. only slot value is changed (example: body part is ear or lear but slot can be both lear or rear based on slot availability)

**Comment by gawric** [comment]
ok
