### ISSUE TITLE
WeightGauge not working

### ISSUE THREAD

**Issue by gawric** [shnok/l2-unity#45]
![image](https://github.com/user-attachments/assets/0d669c24-0d60-4712-adde-86b9df68f928)
installed 90 need to install auto

**Comment by shnok** [comment]
I havent added the feature yet. Weight is not yet calculated server side

**Comment by gawric** [comment]
I know, but the problem is that the sensor is manually adjusted to 90 pixels.
on the screen this is the corrected version

There will be a ban in the future if you don't fix it. Well, or at least save this issue, if it arises you will know where to look

**Comment by gawric** [comment]
I spent 40 minutes looking for where the problem was :)

**Comment by shnok** [comment]
fixed in https://github.com/shnok/l2-unity/tree/31f92b518b1cad0fb9f2d3562ef740c32b818f4e
